[package]
name = "lfs"
version = "0.2.1"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
keywords = ["unix", "filesystem", "fs"]
license = "MIT"
categories = ["filesystem", "command-line-utilities"]
description = "give information on mounted disks"
repository = "https://github.com/Canop/lfs"
readme = "README.md"

[dependencies]
crossterm = "0.17.7"
file-size = "1.0.3"
libc = "0.2"
minimad = "0.6.6"
termimad = "0.8.28"
thiserror = "1.0"

