[package]
name = "lfs"
version = "0.7.6"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
keywords = ["linux", "filesystem", "fs"]
license = "MIT"
categories = ["filesystem", "command-line-utilities"]
description = "give information on mounted disks"
repository = "https://github.com/Canop/lfs"
readme = "README.md"

[dependencies]
argh = "0.1.3"
crossterm = "0.20.0"
file-size = "1.0.3"
lfs-core = "0.4.2"
minimad = "0.8.0"
serde ="1.0"
serde_json = "1.0"
termimad = "0.14.0"

[patch.crates-io]
#minimad = { path = "../minimad" }
#termimad = { path = "../termimad" }
#lfs-core = { path = "../lfs-core" }
