[package]
name = "lfs"
version = "1.2.0"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
keywords = ["linux", "filesystem", "fs"]
license = "MIT"
categories = ["filesystem", "command-line-utilities"]
description = "give information on mounted disks"
repository = "https://github.com/Canop/lfs"
readme = "README.md"

[dependencies]
argh = "0.1.4"
crossterm = "0.21.0"
file-size = "1.0.3"
lfs-core = "0.5.0"
minimad = "0.9.0"
serde ="1.0"
serde_json = "1.0"
termimad = "0.16.3"

[patch.crates-io]
# minimad = { path = "../minimad" }
# termimad = { path = "../termimad" }
#lfs-core = { path = "../lfs-core" }
